# Writes OUTPUT, a C++ source defining maya::build_info(), with the source revision and the build's
# configuration. Run at build time, so the revision is current; the file is rewritten only when its
# contents change, so unchanged builds do not recompile it.
# Usage: cmake -DSOURCE=<repo> -DOUTPUT=<file.cpp> -DBUILD_TYPE=... -DSANITIZERS=... -DCOMPILER=... -P build_info.cmake
set(revision "unknown")
find_program(GIT_EXECUTABLE git)
if(GIT_EXECUTABLE)
    execute_process(COMMAND ${GIT_EXECUTABLE} -C "${SOURCE}" describe --always --dirty --abbrev=12
                    OUTPUT_VARIABLE described RESULT_VARIABLE result OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(result EQUAL 0 AND described)
        set(revision "${described}")
    endif()
    # A dirty tree also names its uncommitted changes (tracked edits and untracked files), so builds of
    # different dirty trees differ.
    if(revision MATCHES "-dirty$")
        execute_process(COMMAND ${GIT_EXECUTABLE} -C "${SOURCE}" diff HEAD --no-ext-diff --binary
                        OUTPUT_VARIABLE changes ERROR_QUIET)
        execute_process(COMMAND ${GIT_EXECUTABLE} -C "${SOURCE}" ls-files --others --exclude-standard
                        OUTPUT_VARIABLE untracked OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if(untracked)
            string(REPLACE "\n" ";" untracked "${untracked}")
            foreach(path IN LISTS untracked)
                if(EXISTS "${SOURCE}/${path}" AND NOT IS_DIRECTORY "${SOURCE}/${path}")
                    file(SHA1 "${SOURCE}/${path}" digest)
                    string(APPEND changes "${path} ${digest}\n")
                endif()
            endforeach()
        endif()
        string(SHA1 digest "${changes}")
        string(SUBSTRING "${digest}" 0 12 digest)
        set(revision "${revision}-${digest}")
    endif()
endif()
if(NOT BUILD_TYPE)
    set(BUILD_TYPE "unspecified")
endif()
if(NOT SANITIZERS)
    set(SANITIZERS "none")
endif()
set(content "// Generated by cmake/build_info.cmake; do not edit.
#include \"maya/core/build_info.hpp\"
namespace maya {
BuildInfo build_info() {
    return {\"${revision}\", \"${BUILD_TYPE}\", \"${SANITIZERS}\", \"${COMPILER}\"};
}
} // namespace maya
")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
endif()
if(NOT "${previous}" STREQUAL "${content}")
    file(WRITE "${OUTPUT}" "${content}")
endif()
