# Writes OUTPUT, a C++ source defining maya::build_info(), with the source revision and the build's
# configuration. Run at build time, so the revision is current; the file is rewritten only when its
# contents change, so unchanged builds do not recompile it.
# Usage: cmake -DSOURCE=<repo> -DOUTPUT=<file.cpp> -DBUILD_TYPE=... -DSANITIZERS=... -DCOMPILER=... -P build_info.cmake
set(revision "unknown")
find_program(GIT_EXECUTABLE git)
if(GIT_EXECUTABLE)
    execute_process(COMMAND ${GIT_EXECUTABLE} -C "${SOURCE}" describe --always --dirty --abbrev=12
                    OUTPUT_VARIABLE described RESULT_VARIABLE result OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(result EQUAL 0 AND described)
        set(revision "${described}")
    endif()
endif()
if(NOT BUILD_TYPE)
    set(BUILD_TYPE "unspecified")
endif()
if(NOT SANITIZERS)
    set(SANITIZERS "none")
endif()
set(content "// Generated by cmake/build_info.cmake; do not edit.
#include \"build_info.hpp\"
namespace maya {
BuildInfo build_info() {
    return {\"${revision}\", \"${BUILD_TYPE}\", \"${SANITIZERS}\", \"${COMPILER}\"};
}
} // namespace maya
")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
endif()
if(NOT "${previous}" STREQUAL "${content}")
    file(WRITE "${OUTPUT}" "${content}")
endif()
