# Fails when a source, header, or test includes a third-party engine library outside the one place
# allowed to: Jolt Physics only in src/maya/physics/, Luau only in src/maya/simulation/scripting/. As a
# positive control, each place must include its library, so a broken search cannot pass.
# Usage: cmake -DSOURCE=<repository root> -P check_library_headers.cmake
if(NOT SOURCE)
    message(FATAL_ERROR "SOURCE is required")
endif()
file(GLOB_RECURSE files LIST_DIRECTORIES false
    "${SOURCE}/include/*" "${SOURCE}/src/*" "${SOURCE}/apps/*" "${SOURCE}/tests/*.cpp" "${SOURCE}/tests/*.hpp"
    "${SOURCE}/samples/*.cpp" "${SOURCE}/samples/*.hpp")
set(libraries "Jolt" "Luau")
set(Jolt_pattern "^[ \t]*#[ \t]*include[ \t]*[<\"]Jolt/")
set(Jolt_home "src/maya/physics/")
set(Luau_pattern "^[ \t]*#[ \t]*include[ \t]*[<\"](Luau/|lua\\.h|lualib\\.h|luacode\\.h|luaconf\\.h)")
set(Luau_home "src/maya/simulation/scripting/")
set(failures "")
foreach(library IN LISTS libraries)
    set(inside 0)
    set(outside "")
    foreach(file IN LISTS files)
        if(NOT file MATCHES "\\.(h|hpp|cpp|mm)$")
            continue()
        endif()
        file(STRINGS "${file}" includes REGEX "${${library}_pattern}")
        if(NOT includes)
            continue()
        endif()
        file(RELATIVE_PATH relative "${SOURCE}" "${file}")
        if(relative MATCHES "^${${library}_home}")
            math(EXPR inside "${inside} + 1")
        else()
            list(APPEND outside "${relative}")
        endif()
    endforeach()
    if(outside)
        list(JOIN outside ", " outside)
        list(APPEND failures "Only ${${library}_home} may include ${library} headers; found them in ${outside}")
    elseif(inside EQUAL 0)
        list(APPEND failures "No ${library} include was found in ${${library}_home}: the check is not searching the right files")
    else()
        message(STATUS "${library} headers are included only by ${${library}_home} (${inside} files)")
    endif()
endforeach()
if(failures)
    list(JOIN failures "\n" failures)
    message(FATAL_ERROR "${failures}")
endif()
