# Fails when a source, header, or test outside src/maya/physics/ includes a Jolt header. As a positive
# control, MayaPhysics itself must include Jolt, so a broken search cannot pass.
# Usage: cmake -DSOURCE=<repository root> -P check_physics_headers.cmake
if(NOT SOURCE)
    message(FATAL_ERROR "SOURCE is required")
endif()
file(GLOB_RECURSE files LIST_DIRECTORIES false
    "${SOURCE}/include/*" "${SOURCE}/src/*" "${SOURCE}/apps/*" "${SOURCE}/tests/*.cpp" "${SOURCE}/tests/*.hpp"
    "${SOURCE}/samples/*.cpp" "${SOURCE}/samples/*.hpp" "${SOURCE}/prototypes/*")
set(inside 0)
set(outside "")
foreach(file IN LISTS files)
    if(NOT file MATCHES "\\.(h|hpp|cpp|mm)$")
        continue()
    endif()
    file(STRINGS "${file}" includes REGEX "^[ \t]*#[ \t]*include[ \t]*[<\"]Jolt/")
    if(NOT includes)
        continue()
    endif()
    if(file MATCHES "^${SOURCE}/src/maya/physics/")
        math(EXPR inside "${inside} + 1")
    else()
        file(RELATIVE_PATH relative "${SOURCE}" "${file}")
        list(APPEND outside "${relative}")
    endif()
endforeach()
if(outside)
    list(JOIN outside ", " outside)
    message(FATAL_ERROR "Only MayaPhysics (src/maya/physics/) may include Jolt headers; found them in ${outside}")
endif()
if(inside EQUAL 0)
    message(FATAL_ERROR "No Jolt include was found in src/maya/physics/: the check is not searching the right files")
endif()
message(STATUS "Jolt headers are included only by MayaPhysics (${inside} files)")
